%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1
%% Version source: file
-module(login_pb2).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("gpb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type 'CS_server_info'() ::
      #{
       }.

-type 'SC_server_info'() ::
      #{server                  => integer(),       % = 1, optional, 32 bits
        status                  => integer(),       % = 2, optional, 32 bits
        open_date               => unicode:chardata() % = 3, optional
       }.

-type 'CS_user'() ::
      #{uid                     => unicode:chardata() % = 1, optional
       }.

-type 'SC_user.User'() ::
      #{server                  => integer(),       % = 1, optional, 32 bits
        rid                     => integer()        % = 2, optional, 64 bits
       }.

-type 'SC_user'() ::
      #{user                    => ['SC_user.User'()] % = 1, repeated
       }.

-type 'CS_login'() ::
      #{uid                     => unicode:chardata(), % = 1, optional
        server                  => integer(),       % = 2, optional, 32 bits
        info                    => unicode:chardata(), % = 3, optional
        sign                    => unicode:chardata() % = 4, optional
       }.

-type 'SC_login'() ::
      #{code                    => integer()        % = 1, optional, 32 bits
       }.

-export_type(['CS_server_info'/0, 'SC_server_info'/0, 'CS_user'/0, 'SC_user.User'/0, 'SC_user'/0, 'CS_login'/0, 'SC_login'/0]).
-type '$msg_name'() :: 'CS_server_info' | 'SC_server_info' | 'CS_user' | 'SC_user.User' | 'SC_user' | 'CS_login' | 'SC_login'.
-type '$msg'() :: 'CS_server_info'() | 'SC_server_info'() | 'CS_user'() | 'SC_user.User'() | 'SC_user'() | 'CS_login'() | 'SC_login'().
-export_type(['$msg_name'/0, '$msg'/0]).

-spec encode_msg('$msg'(), '$msg_name'()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []).

-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    verify_msg(Msg, MsgName, Opts),
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      'CS_server_info' -> encode_msg_CS_server_info(id(Msg, TrUserData), TrUserData);
      'SC_server_info' -> encode_msg_SC_server_info(id(Msg, TrUserData), TrUserData);
      'CS_user' -> encode_msg_CS_user(id(Msg, TrUserData), TrUserData);
      'SC_user.User' -> 'encode_msg_SC_user.User'(id(Msg, TrUserData), TrUserData);
      'SC_user' -> encode_msg_SC_user(id(Msg, TrUserData), TrUserData);
      'CS_login' -> encode_msg_CS_login(id(Msg, TrUserData), TrUserData);
      'SC_login' -> encode_msg_SC_login(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_CS_server_info(_Msg, _TrUserData) -> <<>>.

encode_msg_SC_server_info(Msg, TrUserData) -> encode_msg_SC_server_info(Msg, <<>>, TrUserData).


encode_msg_SC_server_info(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{server := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 if TrF1 =:= 0 -> Bin;
		    true -> e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
		 end
	       end;
	   _ -> Bin
	 end,
    B2 = case M of
	   #{status := F2} ->
	       begin
		 TrF2 = id(F2, TrUserData),
		 if TrF2 =:= 0 -> B1;
		    true -> e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData)
		 end
	       end;
	   _ -> B1
	 end,
    case M of
      #{open_date := F3} ->
	  begin
	    TrF3 = id(F3, TrUserData),
	    case is_empty_string(TrF3) of
	      true -> B2;
	      false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
	    end
	  end;
      _ -> B2
    end.

encode_msg_CS_user(Msg, TrUserData) -> encode_msg_CS_user(Msg, <<>>, TrUserData).


encode_msg_CS_user(#{} = M, Bin, TrUserData) ->
    case M of
      #{uid := F1} ->
	  begin
	    TrF1 = id(F1, TrUserData),
	    case is_empty_string(TrF1) of
	      true -> Bin;
	      false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
	    end
	  end;
      _ -> Bin
    end.

'encode_msg_SC_user.User'(Msg, TrUserData) -> 'encode_msg_SC_user.User'(Msg, <<>>, TrUserData).


'encode_msg_SC_user.User'(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{server := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 if TrF1 =:= 0 -> Bin;
		    true -> e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
		 end
	       end;
	   _ -> Bin
	 end,
    case M of
      #{rid := F2} ->
	  begin
	    TrF2 = id(F2, TrUserData),
	    if TrF2 =:= 0 -> B1;
	       true -> e_type_int64(TrF2, <<B1/binary, 16>>, TrUserData)
	    end
	  end;
      _ -> B1
    end.

encode_msg_SC_user(Msg, TrUserData) -> encode_msg_SC_user(Msg, <<>>, TrUserData).


encode_msg_SC_user(#{} = M, Bin, TrUserData) ->
    case M of
      #{user := F1} ->
	  TrF1 = id(F1, TrUserData),
	  if TrF1 == [] -> Bin;
	     true -> e_field_SC_user_user(TrF1, Bin, TrUserData)
	  end;
      _ -> Bin
    end.

encode_msg_CS_login(Msg, TrUserData) -> encode_msg_CS_login(Msg, <<>>, TrUserData).


encode_msg_CS_login(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{uid := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 case is_empty_string(TrF1) of
		   true -> Bin;
		   false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
		 end
	       end;
	   _ -> Bin
	 end,
    B2 = case M of
	   #{server := F2} ->
	       begin
		 TrF2 = id(F2, TrUserData),
		 if TrF2 =:= 0 -> B1;
		    true -> e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData)
		 end
	       end;
	   _ -> B1
	 end,
    B3 = case M of
	   #{info := F3} ->
	       begin
		 TrF3 = id(F3, TrUserData),
		 case is_empty_string(TrF3) of
		   true -> B2;
		   false -> e_type_string(TrF3, <<B2/binary, 26>>, TrUserData)
		 end
	       end;
	   _ -> B2
	 end,
    case M of
      #{sign := F4} ->
	  begin
	    TrF4 = id(F4, TrUserData),
	    case is_empty_string(TrF4) of
	      true -> B3;
	      false -> e_type_string(TrF4, <<B3/binary, 34>>, TrUserData)
	    end
	  end;
      _ -> B3
    end.

encode_msg_SC_login(Msg, TrUserData) -> encode_msg_SC_login(Msg, <<>>, TrUserData).


encode_msg_SC_login(#{} = M, Bin, TrUserData) ->
    case M of
      #{code := F1} ->
	  begin
	    TrF1 = id(F1, TrUserData),
	    if TrF1 =:= 0 -> Bin;
	       true -> e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
	    end
	  end;
      _ -> Bin
    end.

e_mfield_SC_user_user(Msg, Bin, TrUserData) -> SubBin = 'encode_msg_SC_user.User'(Msg, <<>>, TrUserData), Bin2 = e_varint(byte_size(SubBin), Bin), <<Bin2/binary, SubBin/binary>>.

e_field_SC_user_user([Elem | Rest], Bin, TrUserData) -> Bin2 = <<Bin/binary, 10>>, Bin3 = e_mfield_SC_user_user(id(Elem, TrUserData), Bin2, TrUserData), e_field_SC_user_user(Rest, Bin3, TrUserData);
e_field_SC_user_user([], Bin, _TrUserData) -> Bin.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) -> <<N:64/unsigned-native>> = <<Value:64/signed-native>>, e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) -> Utf8 = unicode:characters_to_binary(S), Bin2 = e_varint(byte_size(Utf8), Bin), <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) -> Bin2 = e_varint(byte_size(Bytes), Bin), <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) -> BytesBin = iolist_to_binary(Bytes), Bin2 = e_varint(byte_size(BytesBin), Bin), <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
	     {varint, FNum, N} -> BinF = e_varint(FNum bsl 3, Bin), e_varint(N, BinF);
	     {length_delimited, FNum, Data} -> BinF = e_varint(FNum bsl 3 bor 2, Bin), BinL = e_varint(byte_size(Data), BinF), <<BinL/binary, Data/binary>>;
	     {group, FNum, GroupFields} -> Bin1 = e_varint(FNum bsl 3 bor 3, Bin), Bin2 = e_unknown_elems(GroupFields, Bin1), e_varint(FNum bsl 3 bor 4, Bin2);
	     {fixed32, FNum, V} -> BinF = e_varint(FNum bsl 3 bor 5, Bin), <<BinF/binary, V:32/little>>;
	     {fixed64, FNum, V} -> BinF = e_varint(FNum bsl 3 bor 1, Bin), <<BinF/binary, V:64/little>>
	   end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) -> Bin2 = <<Bin/binary, (N band 127 bor 128)>>, e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
      true -> true;
      false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) -> TrUserData = proplists:get_value(user_data, Opts), decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('CS_server_info', Bin, TrUserData) -> id(decode_msg_CS_server_info(Bin, TrUserData), TrUserData);
decode_msg_2_doit('SC_server_info', Bin, TrUserData) -> id(decode_msg_SC_server_info(Bin, TrUserData), TrUserData);
decode_msg_2_doit('CS_user', Bin, TrUserData) -> id(decode_msg_CS_user(Bin, TrUserData), TrUserData);
decode_msg_2_doit('SC_user.User', Bin, TrUserData) -> id('decode_msg_SC_user.User'(Bin, TrUserData), TrUserData);
decode_msg_2_doit('SC_user', Bin, TrUserData) -> id(decode_msg_SC_user(Bin, TrUserData), TrUserData);
decode_msg_2_doit('CS_login', Bin, TrUserData) -> id(decode_msg_CS_login(Bin, TrUserData), TrUserData);
decode_msg_2_doit('SC_login', Bin, TrUserData) -> id(decode_msg_SC_login(Bin, TrUserData), TrUserData).



decode_msg_CS_server_info(Bin, TrUserData) -> dfp_read_field_def_CS_server_info(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_CS_server_info(<<>>, 0, 0, _, _) -> #{};
dfp_read_field_def_CS_server_info(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_CS_server_info(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_CS_server_info(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_CS_server_info(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_CS_server_info(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
      0 -> skip_varint_CS_server_info(Rest, 0, 0, Key bsr 3, TrUserData);
      1 -> skip_64_CS_server_info(Rest, 0, 0, Key bsr 3, TrUserData);
      2 -> skip_length_delimited_CS_server_info(Rest, 0, 0, Key bsr 3, TrUserData);
      3 -> skip_group_CS_server_info(Rest, 0, 0, Key bsr 3, TrUserData);
      5 -> skip_32_CS_server_info(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_CS_server_info(<<>>, 0, 0, _, _) -> #{}.

skip_varint_CS_server_info(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_CS_server_info(Rest, Z1, Z2, F, TrUserData);
skip_varint_CS_server_info(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_CS_server_info(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_CS_server_info(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_CS_server_info(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_CS_server_info(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_CS_server_info(Rest2, 0, 0, F, TrUserData).

skip_group_CS_server_info(Bin, _, Z2, FNum, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_CS_server_info(Rest, 0, Z2, FNum, TrUserData).

skip_32_CS_server_info(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_CS_server_info(Rest, Z1, Z2, F, TrUserData).

skip_64_CS_server_info(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_CS_server_info(Rest, Z1, Z2, F, TrUserData).

decode_msg_SC_server_info(Bin, TrUserData) -> dfp_read_field_def_SC_server_info(Bin, 0, 0, 0, id(0, TrUserData), id(0, TrUserData), id([], TrUserData), TrUserData).

dfp_read_field_def_SC_server_info(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_SC_server_info_server(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_SC_server_info(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_SC_server_info_status(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_SC_server_info(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_SC_server_info_open_date(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_SC_server_info(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #{server => F@_1, status => F@_2, open_date => F@_3};
dfp_read_field_def_SC_server_info(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dg_read_field_def_SC_server_info(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

dg_read_field_def_SC_server_info(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> dg_read_field_def_SC_server_info(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_SC_server_info(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_SC_server_info_server(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
      16 -> d_field_SC_server_info_status(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
      26 -> d_field_SC_server_info_open_date(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_SC_server_info(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    1 -> skip_64_SC_server_info(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    2 -> skip_length_delimited_SC_server_info(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    3 -> skip_group_SC_server_info(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
	    5 -> skip_32_SC_server_info(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
	  end
    end;
dg_read_field_def_SC_server_info(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) -> #{server => F@_1, status => F@_2, open_date => F@_3}.

d_field_SC_server_info_server(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_SC_server_info_server(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_SC_server_info_server(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_SC_server_info(RestF, 0, 0, F, NewFValue, F@_2, F@_3, TrUserData).

d_field_SC_server_info_status(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_SC_server_info_status(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_SC_server_info_status(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_SC_server_info(RestF, 0, 0, F, F@_1, NewFValue, F@_3, TrUserData).

d_field_SC_server_info_open_date(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_SC_server_info_open_date(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_SC_server_info_open_date(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Utf8:Len/binary, Rest2/binary>> = Rest, {id(unicode:characters_to_list(Utf8, unicode), TrUserData), Rest2} end, dfp_read_field_def_SC_server_info(RestF, 0, 0, F, F@_1, F@_2, NewFValue, TrUserData).

skip_varint_SC_server_info(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> skip_varint_SC_server_info(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
skip_varint_SC_server_info(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_SC_server_info(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_length_delimited_SC_server_info(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> skip_length_delimited_SC_server_info(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_SC_server_info(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_SC_server_info(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

skip_group_SC_server_info(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_SC_server_info(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

skip_32_SC_server_info(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_SC_server_info(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_64_SC_server_info(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_SC_server_info(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

decode_msg_CS_user(Bin, TrUserData) -> dfp_read_field_def_CS_user(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_CS_user(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_CS_user_uid(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_CS_user(<<>>, 0, 0, _, F@_1, _) -> #{uid => F@_1};
dfp_read_field_def_CS_user(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_CS_user(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_CS_user(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_CS_user(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_CS_user(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_CS_user_uid(Rest, 0, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_CS_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    1 -> skip_64_CS_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    2 -> skip_length_delimited_CS_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    3 -> skip_group_CS_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    5 -> skip_32_CS_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_CS_user(<<>>, 0, 0, _, F@_1, _) -> #{uid => F@_1}.

d_field_CS_user_uid(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_CS_user_uid(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_CS_user_uid(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Utf8:Len/binary, Rest2/binary>> = Rest, {id(unicode:characters_to_list(Utf8, unicode), TrUserData), Rest2} end, dfp_read_field_def_CS_user(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_CS_user(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_CS_user(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_CS_user(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_CS_user(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_CS_user(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_CS_user(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_CS_user(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_CS_user(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_CS_user(Bin, _, Z2, FNum, F@_1, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_CS_user(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_CS_user(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_CS_user(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_CS_user(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_CS_user(Rest, Z1, Z2, F, F@_1, TrUserData).

'decode_msg_SC_user.User'(Bin, TrUserData) -> 'dfp_read_field_def_SC_user.User'(Bin, 0, 0, 0, id(0, TrUserData), id(0, TrUserData), TrUserData).

'dfp_read_field_def_SC_user.User'(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_SC_user.User_server'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_SC_user.User'(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'd_field_SC_user.User_rid'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'dfp_read_field_def_SC_user.User'(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{server => F@_1, rid => F@_2};
'dfp_read_field_def_SC_user.User'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dg_read_field_def_SC_user.User'(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

'dg_read_field_def_SC_user.User'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> 'dg_read_field_def_SC_user.User'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'dg_read_field_def_SC_user.User'(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> 'd_field_SC_user.User_server'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
      16 -> 'd_field_SC_user.User_rid'(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> 'skip_varint_SC_user.User'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    1 -> 'skip_64_SC_user.User'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    2 -> 'skip_length_delimited_SC_user.User'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    3 -> 'skip_group_SC_user.User'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
	    5 -> 'skip_32_SC_user.User'(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
	  end
    end;
'dg_read_field_def_SC_user.User'(<<>>, 0, 0, _, F@_1, F@_2, _) -> #{server => F@_1, rid => F@_2}.

'd_field_SC_user.User_server'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_SC_user.User_server'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_SC_user.User_server'(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, 'dfp_read_field_def_SC_user.User'(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

'd_field_SC_user.User_rid'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'd_field_SC_user.User_rid'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'd_field_SC_user.User_rid'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest}, 'dfp_read_field_def_SC_user.User'(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

'skip_varint_SC_user.User'(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'skip_varint_SC_user.User'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
'skip_varint_SC_user.User'(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_SC_user.User'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_length_delimited_SC_user.User'(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> 'skip_length_delimited_SC_user.User'(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
'skip_length_delimited_SC_user.User'(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, 'dfp_read_field_def_SC_user.User'(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

'skip_group_SC_user.User'(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) -> {_, Rest} = read_group(Bin, FNum), 'dfp_read_field_def_SC_user.User'(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

'skip_32_SC_user.User'(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_SC_user.User'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

'skip_64_SC_user.User'(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> 'dfp_read_field_def_SC_user.User'(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_SC_user(Bin, TrUserData) -> dfp_read_field_def_SC_user(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_SC_user(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_SC_user_user(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_SC_user(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{user => lists_reverse(R1, TrUserData)}
    end;
dfp_read_field_def_SC_user(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_SC_user(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_SC_user(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_SC_user(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_SC_user(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_SC_user_user(Rest, 0, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_SC_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    1 -> skip_64_SC_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    2 -> skip_length_delimited_SC_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    3 -> skip_group_SC_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    5 -> skip_32_SC_user(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_SC_user(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{user => lists_reverse(R1, TrUserData)}
    end.

d_field_SC_user_user(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_SC_user_user(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_SC_user_user(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id('decode_msg_SC_user.User'(Bs, TrUserData), TrUserData), Rest2} end, dfp_read_field_def_SC_user(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_SC_user(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_SC_user(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_SC_user(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_SC_user(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_SC_user(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_SC_user(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_SC_user(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_SC_user(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_SC_user(Bin, _, Z2, FNum, F@_1, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_SC_user(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_SC_user(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_SC_user(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_SC_user(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_SC_user(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_CS_login(Bin, TrUserData) -> dfp_read_field_def_CS_login(Bin, 0, 0, 0, id([], TrUserData), id(0, TrUserData), id([], TrUserData), id([], TrUserData), TrUserData).

dfp_read_field_def_CS_login(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_CS_login_uid(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_CS_login(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_CS_login_server(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_CS_login(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_CS_login_info(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_CS_login(<<34, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_CS_login_sign(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_CS_login(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #{uid => F@_1, server => F@_2, info => F@_3, sign => F@_4};
dfp_read_field_def_CS_login(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dg_read_field_def_CS_login(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

dg_read_field_def_CS_login(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> dg_read_field_def_CS_login(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_CS_login(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_CS_login_uid(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
      16 -> d_field_CS_login_server(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
      26 -> d_field_CS_login_info(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
      34 -> d_field_CS_login_sign(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_CS_login(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
	    1 -> skip_64_CS_login(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
	    2 -> skip_length_delimited_CS_login(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
	    3 -> skip_group_CS_login(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
	    5 -> skip_32_CS_login(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
	  end
    end;
dg_read_field_def_CS_login(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #{uid => F@_1, server => F@_2, info => F@_3, sign => F@_4}.

d_field_CS_login_uid(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_CS_login_uid(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_CS_login_uid(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Utf8:Len/binary, Rest2/binary>> = Rest, {id(unicode:characters_to_list(Utf8, unicode), TrUserData), Rest2} end, dfp_read_field_def_CS_login(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

d_field_CS_login_server(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_CS_login_server(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_CS_login_server(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_CS_login(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData).

d_field_CS_login_info(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_CS_login_info(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_CS_login_info(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Utf8:Len/binary, Rest2/binary>> = Rest, {id(unicode:characters_to_list(Utf8, unicode), TrUserData), Rest2} end, dfp_read_field_def_CS_login(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

d_field_CS_login_sign(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_CS_login_sign(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_CS_login_sign(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Utf8:Len/binary, Rest2/binary>> = Rest, {id(unicode:characters_to_list(Utf8, unicode), TrUserData), Rest2} end, dfp_read_field_def_CS_login(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, TrUserData).

skip_varint_CS_login(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> skip_varint_CS_login(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_varint_CS_login(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_CS_login(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_length_delimited_CS_login(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> skip_length_delimited_CS_login(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_length_delimited_CS_login(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_CS_login(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_group_CS_login(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_CS_login(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_32_CS_login(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_CS_login(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_64_CS_login(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_CS_login(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

decode_msg_SC_login(Bin, TrUserData) -> dfp_read_field_def_SC_login(Bin, 0, 0, 0, id(0, TrUserData), TrUserData).

dfp_read_field_def_SC_login(<<8, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_SC_login_code(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_SC_login(<<>>, 0, 0, _, F@_1, _) -> #{code => F@_1};
dfp_read_field_def_SC_login(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_SC_login(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_SC_login(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_SC_login(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_SC_login(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 -> d_field_SC_login_code(Rest, 0, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_SC_login(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    1 -> skip_64_SC_login(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    2 -> skip_length_delimited_SC_login(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    3 -> skip_group_SC_login(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
	    5 -> skip_32_SC_login(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_SC_login(<<>>, 0, 0, _, F@_1, _) -> #{code => F@_1}.

d_field_SC_login_code(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_SC_login_code(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_SC_login_code(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest}, dfp_read_field_def_SC_login(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_SC_login(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_SC_login(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_SC_login(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_SC_login(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_SC_login(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_SC_login(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_SC_login(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) -> Length = X bsl N + Acc, <<_:Length/binary, Rest2/binary>> = Rest, dfp_read_field_def_SC_login(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_SC_login(Bin, _, Z2, FNum, F@_1, TrUserData) -> {_, Rest} = read_group(Bin, FNum), dfp_read_field_def_SC_login(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_SC_login(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_SC_login(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_SC_login(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_SC_login(Rest, Z1, Z2, F, F@_1, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      'CS_server_info' -> merge_msg_CS_server_info(Prev, New, TrUserData);
      'SC_server_info' -> merge_msg_SC_server_info(Prev, New, TrUserData);
      'CS_user' -> merge_msg_CS_user(Prev, New, TrUserData);
      'SC_user.User' -> 'merge_msg_SC_user.User'(Prev, New, TrUserData);
      'SC_user' -> merge_msg_SC_user(Prev, New, TrUserData);
      'CS_login' -> merge_msg_CS_login(Prev, New, TrUserData);
      'SC_login' -> merge_msg_SC_login(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_CS_server_info/3}).
merge_msg_CS_server_info(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_SC_server_info/3}).
merge_msg_SC_server_info(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{server := NFserver}} -> S1#{server => NFserver};
	   {#{server := PFserver}, _} -> S1#{server => PFserver};
	   _ -> S1
	 end,
    S3 = case {PMsg, NMsg} of
	   {_, #{status := NFstatus}} -> S2#{status => NFstatus};
	   {#{status := PFstatus}, _} -> S2#{status => PFstatus};
	   _ -> S2
	 end,
    case {PMsg, NMsg} of
      {_, #{open_date := NFopen_date}} -> S3#{open_date => NFopen_date};
      {#{open_date := PFopen_date}, _} -> S3#{open_date => PFopen_date};
      _ -> S3
    end.

-compile({nowarn_unused_function,merge_msg_CS_user/3}).
merge_msg_CS_user(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
      {_, #{uid := NFuid}} -> S1#{uid => NFuid};
      {#{uid := PFuid}, _} -> S1#{uid => PFuid};
      _ -> S1
    end.

-compile({nowarn_unused_function,'merge_msg_SC_user.User'/3}).
'merge_msg_SC_user.User'(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{server := NFserver}} -> S1#{server => NFserver};
	   {#{server := PFserver}, _} -> S1#{server => PFserver};
	   _ -> S1
	 end,
    case {PMsg, NMsg} of
      {_, #{rid := NFrid}} -> S2#{rid => NFrid};
      {#{rid := PFrid}, _} -> S2#{rid => PFrid};
      _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_SC_user/3}).
merge_msg_SC_user(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
      {#{user := PFuser}, #{user := NFuser}} -> S1#{user => 'erlang_++'(PFuser, NFuser, TrUserData)};
      {_, #{user := NFuser}} -> S1#{user => NFuser};
      {#{user := PFuser}, _} -> S1#{user => PFuser};
      {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_CS_login/3}).
merge_msg_CS_login(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{uid := NFuid}} -> S1#{uid => NFuid};
	   {#{uid := PFuid}, _} -> S1#{uid => PFuid};
	   _ -> S1
	 end,
    S3 = case {PMsg, NMsg} of
	   {_, #{server := NFserver}} -> S2#{server => NFserver};
	   {#{server := PFserver}, _} -> S2#{server => PFserver};
	   _ -> S2
	 end,
    S4 = case {PMsg, NMsg} of
	   {_, #{info := NFinfo}} -> S3#{info => NFinfo};
	   {#{info := PFinfo}, _} -> S3#{info => PFinfo};
	   _ -> S3
	 end,
    case {PMsg, NMsg} of
      {_, #{sign := NFsign}} -> S4#{sign => NFsign};
      {#{sign := PFsign}, _} -> S4#{sign => PFsign};
      _ -> S4
    end.

-compile({nowarn_unused_function,merge_msg_SC_login/3}).
merge_msg_SC_login(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
      {_, #{code := NFcode}} -> S1#{code => NFcode};
      {#{code := PFcode}, _} -> S1#{code => PFcode};
      _ -> S1
    end.


verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      'CS_server_info' -> v_msg_CS_server_info(Msg, [MsgName], TrUserData);
      'SC_server_info' -> v_msg_SC_server_info(Msg, [MsgName], TrUserData);
      'CS_user' -> v_msg_CS_user(Msg, [MsgName], TrUserData);
      'SC_user.User' -> 'v_msg_SC_user.User'(Msg, [MsgName], TrUserData);
      'SC_user' -> v_msg_SC_user(Msg, [MsgName], TrUserData);
      'CS_login' -> v_msg_CS_login(Msg, [MsgName], TrUserData);
      'SC_login' -> v_msg_SC_login(Msg, [MsgName], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_CS_server_info/3}).
-dialyzer({nowarn_function,v_msg_CS_server_info/3}).
v_msg_CS_server_info(#{} = M, Path, _) -> lists:foreach(fun (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path) end, maps:keys(M)), ok;
v_msg_CS_server_info(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'CS_server_info'}, M, Path);
v_msg_CS_server_info(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'CS_server_info'}, X, Path).

-compile({nowarn_unused_function,v_msg_SC_server_info/3}).
-dialyzer({nowarn_function,v_msg_SC_server_info/3}).
v_msg_SC_server_info(#{} = M, Path, TrUserData) ->
    case M of
      #{server := F1} -> v_type_int32(F1, [server | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{status := F2} -> v_type_int32(F2, [status | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{open_date := F3} -> v_type_string(F3, [open_date | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (server) -> ok;
		      (status) -> ok;
		      (open_date) -> ok;
		      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_SC_server_info(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'SC_server_info'}, M, Path);
v_msg_SC_server_info(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'SC_server_info'}, X, Path).

-compile({nowarn_unused_function,v_msg_CS_user/3}).
-dialyzer({nowarn_function,v_msg_CS_user/3}).
v_msg_CS_user(#{} = M, Path, TrUserData) ->
    case M of
      #{uid := F1} -> v_type_string(F1, [uid | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (uid) -> ok;
		      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_CS_user(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'CS_user'}, M, Path);
v_msg_CS_user(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'CS_user'}, X, Path).

-compile({nowarn_unused_function,'v_msg_SC_user.User'/3}).
-dialyzer({nowarn_function,'v_msg_SC_user.User'/3}).
'v_msg_SC_user.User'(#{} = M, Path, TrUserData) ->
    case M of
      #{server := F1} -> v_type_int32(F1, [server | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{rid := F2} -> v_type_int64(F2, [rid | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (server) -> ok;
		      (rid) -> ok;
		      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
'v_msg_SC_user.User'(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'SC_user.User'}, M, Path);
'v_msg_SC_user.User'(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'SC_user.User'}, X, Path).

-compile({nowarn_unused_function,v_msg_SC_user/3}).
-dialyzer({nowarn_function,v_msg_SC_user/3}).
v_msg_SC_user(#{} = M, Path, TrUserData) ->
    case M of
      #{user := F1} ->
	  if is_list(F1) -> _ = ['v_msg_SC_user.User'(Elem, [user | Path], TrUserData) || Elem <- F1], ok;
	     true -> mk_type_error({invalid_list_of, {msg, 'SC_user.User'}}, F1, [user | Path])
	  end;
      _ -> ok
    end,
    lists:foreach(fun (user) -> ok;
		      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_SC_user(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'SC_user'}, M, Path);
v_msg_SC_user(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'SC_user'}, X, Path).

-compile({nowarn_unused_function,v_msg_CS_login/3}).
-dialyzer({nowarn_function,v_msg_CS_login/3}).
v_msg_CS_login(#{} = M, Path, TrUserData) ->
    case M of
      #{uid := F1} -> v_type_string(F1, [uid | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{server := F2} -> v_type_int32(F2, [server | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{info := F3} -> v_type_string(F3, [info | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{sign := F4} -> v_type_string(F4, [sign | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (uid) -> ok;
		      (server) -> ok;
		      (info) -> ok;
		      (sign) -> ok;
		      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_CS_login(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'CS_login'}, M, Path);
v_msg_CS_login(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'CS_login'}, X, Path).

-compile({nowarn_unused_function,v_msg_SC_login/3}).
-dialyzer({nowarn_function,v_msg_SC_login/3}).
v_msg_SC_login(#{} = M, Path, TrUserData) ->
    case M of
      #{code := F1} -> v_type_int32(F1, [code | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (code) -> ok;
		      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_SC_login(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), 'SC_login'}, M, Path);
v_msg_SC_login(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'SC_login'}, X, Path).

-compile({nowarn_unused_function,v_type_int32/3}).
-dialyzer({nowarn_function,v_type_int32/3}).
v_type_int32(N, _Path, _TrUserData) when -2147483648 =< N, N =< 2147483647 -> ok;
v_type_int32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int32, signed, 32}, N, Path);
v_type_int32(X, Path, _TrUserData) -> mk_type_error({bad_integer, int32, signed, 32}, X, Path).

-compile({nowarn_unused_function,v_type_int64/3}).
-dialyzer({nowarn_function,v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when -9223372036854775808 =< N, N =< 9223372036854775807 -> ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) -> mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) -> Path2 = prettify_path(Path), erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, 'CS_server_info'}, []},
     {{msg, 'SC_server_info'},
      [#field{name = server, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = status, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
       #field{name = open_date, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}]},
     {{msg, 'CS_user'}, [#field{name = uid, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}]},
     {{msg, 'SC_user.User'}, [#field{name = server, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = rid, fnum = 2, rnum = 3, type = int64, occurrence = optional, opts = []}]},
     {{msg, 'SC_user'}, [#field{name = user, fnum = 1, rnum = 2, type = {msg, 'SC_user.User'}, occurrence = repeated, opts = []}]},
     {{msg, 'CS_login'},
      [#field{name = uid, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = server, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
       #field{name = info, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}, #field{name = sign, fnum = 4, rnum = 5, type = string, occurrence = optional, opts = []}]},
     {{msg, 'SC_login'}, [#field{name = code, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}]}].


get_msg_names() -> ['CS_server_info', 'SC_server_info', 'CS_user', 'SC_user.User', 'SC_user', 'CS_login', 'SC_login'].


get_group_names() -> [].


get_msg_or_group_names() -> ['CS_server_info', 'SC_server_info', 'CS_user', 'SC_user.User', 'SC_user', 'CS_login', 'SC_login'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def('CS_server_info') -> [];
find_msg_def('SC_server_info') ->
    [#field{name = server, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = status, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
     #field{name = open_date, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}];
find_msg_def('CS_user') -> [#field{name = uid, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}];
find_msg_def('SC_user.User') -> [#field{name = server, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}, #field{name = rid, fnum = 2, rnum = 3, type = int64, occurrence = optional, opts = []}];
find_msg_def('SC_user') -> [#field{name = user, fnum = 1, rnum = 2, type = {msg, 'SC_user.User'}, occurrence = repeated, opts = []}];
find_msg_def('CS_login') ->
    [#field{name = uid, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = server, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
     #field{name = info, fnum = 3, rnum = 4, type = string, occurrence = optional, opts = []}, #field{name = sign, fnum = 4, rnum = 5, type = string, occurrence = optional, opts = []}];
find_msg_def('SC_login') -> [#field{name = code, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"proto.CS_server_info">>) -> 'CS_server_info';
fqbin_to_msg_name(<<"proto.SC_server_info">>) -> 'SC_server_info';
fqbin_to_msg_name(<<"proto.CS_user">>) -> 'CS_user';
fqbin_to_msg_name(<<"proto.SC_user.User">>) -> 'SC_user.User';
fqbin_to_msg_name(<<"proto.SC_user">>) -> 'SC_user';
fqbin_to_msg_name(<<"proto.CS_login">>) -> 'CS_login';
fqbin_to_msg_name(<<"proto.SC_login">>) -> 'SC_login';
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin('CS_server_info') -> <<"proto.CS_server_info">>;
msg_name_to_fqbin('SC_server_info') -> <<"proto.SC_server_info">>;
msg_name_to_fqbin('CS_user') -> <<"proto.CS_user">>;
msg_name_to_fqbin('SC_user.User') -> <<"proto.SC_user.User">>;
msg_name_to_fqbin('SC_user') -> <<"proto.SC_user">>;
msg_name_to_fqbin('CS_login') -> <<"proto.CS_login">>;
msg_name_to_fqbin('SC_login') -> <<"proto.SC_login">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> proto.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "login.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["login.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["login"].


get_msg_containment("login") -> ['CS_login', 'CS_server_info', 'CS_user', 'SC_login', 'SC_server_info', 'SC_user', 'SC_user.User'];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("login") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("login") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("login") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("login") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"proto.SC_user.User">>) -> "login";
get_proto_by_msg_name_as_fqbin(<<"proto.SC_user">>) -> "login";
get_proto_by_msg_name_as_fqbin(<<"proto.CS_user">>) -> "login";
get_proto_by_msg_name_as_fqbin(<<"proto.SC_login">>) -> "login";
get_proto_by_msg_name_as_fqbin(<<"proto.CS_login">>) -> "login";
get_proto_by_msg_name_as_fqbin(<<"proto.SC_server_info">>) -> "login";
get_proto_by_msg_name_as_fqbin(<<"proto.CS_server_info">>) -> "login";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.19.1".

gpb_version_as_list() ->
    [4,19,1].

gpb_version_source() ->
    "file".
